# Generated by Django 4.2.5 on 2023-09-12 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('origin', models.CharField(blank=True, max_length=25, null=True)),
                ('key', models.CharField(blank=True, max_length=25, null=True)),
                ('value', models.CharField(blank=True, max_length=25, null=True)),
                ('source_path', models.CharField(blank=True, max_length=55, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoginItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.CharField(blank=True, max_length=25, null=True)),
                ('name', models.CharField(blank=True, max_length=25, null=True)),
                ('value', models.CharField(blank=True, max_length=25, null=True)),
                ('count', models.CharField(blank=True, max_length=25, null=True)),
                ('interpretation', models.CharField(blank=True, max_length=25, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=25, null=True)),
                ('title', models.CharField(blank=True, max_length=25, null=True)),
                ('visit_time', models.CharField(blank=True, max_length=25, null=True)),
                ('visit_source', models.CharField(blank=True, max_length=25, null=True)),
                ('visit_duration', models.CharField(blank=True, max_length=25, null=True)),
                ('visit_count', models.CharField(blank=True, max_length=25, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(blank=True, max_length=25, null=True)),
                ('end_time', models.CharField(blank=True, max_length=25, null=True)),
                ('download_id', models.CharField(blank=True, max_length=25, null=True)),
                ('download_url', models.CharField(blank=True, max_length=25, null=True)),
                ('download_target_path', models.CharField(blank=True, max_length=25, null=True)),
                ('download_danger_type', models.CharField(blank=True, max_length=25, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='download_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cookie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.CharField(blank=True, max_length=25, null=True)),
                ('name', models.CharField(blank=True, max_length=25, null=True)),
                ('value', models.CharField(blank=True, max_length=25, null=True)),
                ('path', models.CharField(blank=True, max_length=25, null=True)),
                ('priority', models.CharField(blank=True, max_length=25, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cookie_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chrome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('path', models.FilePathField(allow_files=False, allow_folders=True)),
                ('cookies', models.ManyToManyField(to='metadata.cookie')),
                ('downloads', models.ManyToManyField(to='metadata.download')),
                ('history', models.ManyToManyField(to='metadata.history')),
                ('logins', models.ManyToManyField(to='metadata.loginitem')),
                ('storages', models.ManyToManyField(to='metadata.localstorage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chrome_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
