# Generated by Django 4.2.5 on 2023-09-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chrome',
            name='path',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
