# Generated by Django 4.2.5 on 2023-09-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0002_alter_chrome_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chrome',
            name='path',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
