# Generated by Django 4.2.5 on 2023-09-13 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('metadata', '0004_alter_loginitem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chrome',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chrome_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
