# Generated by Django 4.2.5 on 2023-09-14 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0005_alter_chrome_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chrome',
            old_name='path',
            new_name='pc_username',
        ),
    ]
