# Generated by Django 4.2.5 on 2023-09-14 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0007_remove_cookie_creation_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='download',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='download',
            name='start_time',
        ),
    ]
