# Generated by Django 4.2.5 on 2023-09-12 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='state_of_residence',
        ),
    ]
